## COMP3670/6670 Programming Assignment 1 - Linear Algebra and Analytic Geometry
---

**Enter Your Student ID:** u7351505

**Your Name:** Yifan Luo
    
**Deadline:** 8.28, 11:59 PM

**Submit:** Write your answers in this file, and submit a single Jupyter Notebook file (.ipynb) on Wattle. Rename this file with your student number as 'uXXXXXXX.ipynb'.

**Enter Discussion Partner IDs Below:**
You could add more IDs with the same markdown format above.



---
**Marking distribution for the assignment**

- Task1 = 10%
- Task2 = 50%
- Task3 = 40%

**You will get full marks if your program passes all the tests; you will get partial marks if it passes some cases. There is no process marks (we do not look into your codes).**

## Task 0: Introduction
---

**NOTE:** *This part of the first assignment is by necessity somewhat tedious as its primary purpose is to introduce syntax, how to access and understand the Numpy documentation and some very basic concepts. If you are already familiar with Numpy, you can just read the **TASK** headings and complete the questions without worrying about all the additional information. This is designed for people who have never seen Numpy before, so it's a very easy 1st year style introduction to just introduce syntax.*

*As this is a third year subject, it is assumed you already know to to program well (but may be unfamiliar with Python and Numpy).*

---

Arguably the most fundamental tool needed to engage with machine learning in Python is Numpy *(np)*. To include Numpy in any project, simply type the following line at the top of your python file:

In [1]:
# numpy
import numpy as np

!pip install sympy
import sympy as sp

# matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

A Jupyter Notebook is divided into cells, each of which works like a Python module or Latex file. When a cell is run, any cells that follow it will have access to its results. Running the above cell will give all following cells access to the Numpy library.

-----------

   **TASK 0.1:** To run the above cell, select it by clicking on it, hold **shift** and press **return**. If you have succeeded, then the cell will print "Done" just above.


-----------

Numpy is a library of common mathematical data structures and algorithms used in machine learning. For example:

- It allows you to declare vectors and matrices, with all the associated mathematical operations like matrix vector products, matrix addition / subtraction.
- It provides convenient, efficient implementations of algorithms to solve matrix equations, find the inverse of a matrix or perform Eigen decomposition. The implementation of these algorithms is compiled from C code, making Numpy much faster than programming these algorithms yourself in Python.

You'll need to know Numpy inside and out. We'll start by getting you familiar with the easy to access online documentation and performing a few basic operations.

Below I have declared the matrices: 

$$A = 
\begin{bmatrix}
2&3\\
0&1\\
\end{bmatrix}
\\
x = 
\begin{bmatrix}
1\\
3\\
\end{bmatrix}
$$. 

---
**TASK 0.2:** Run the cell below and observe what it prints.


---
(If it throws an error, you have the wrong version of python installed. This entire course will use Python 3, not Python 2)



In [2]:
A = np.array([[2, 3], [0, 1]])
x = np.array([[1], [3]])

#Matrix Multiplication Example
b = A @ x
print('\nMatrix Multiplication')
print(b)


Matrix Multiplication
[[11]
 [ 3]]


The above code illustrates how to perform matrix multiplication. Memorise it. Below are some other basic operations you'll likely need over the coming semester:

In [3]:
#Matrix Addition Example
b = A + x
print('\nMatrix Addition')
print(b)

#Elementwise Multiplication Example
b = A * x
print('\nElementwise Matrix Multiplication')
print(b)

#Extract a single element of a matrix:
print('\nSingle Element Extraction')
b = A[0, 0]
print(b)

#Extract an entire column of a matrix:
print('\nColumn Extraction')
b = A[:, 0]
print(b)

#Extract an entire row of a matrix:
print('\nRow Extraction')
b = A[0, :]
print(b)

#Transpose of a matrix:
print('\nTranspose')
A_Transpose = A.T
print(A_Transpose)


Matrix Addition
[[3 4]
 [3 4]]

Elementwise Matrix Multiplication
[[2 3]
 [0 3]]

Single Element Extraction
2

Column Extraction
[2 0]

Row Extraction
[2 3]

Transpose
[[2 0]
 [3 1]]


## Task1: Solving a system of linear equations
---

A vital part of linear algebra is to know how to solve a system of linear equations. For e.g. 

$$a_{11}x_1+a_{12}x_2 \dots a_{1d}x_d=b_1$$
$$a_{21}x_1+a_{22}x_2 \dots a_{2d}x_d=b_2$$
$$\vdots$$
$$a_{n1}x_1+a_{n2}x_2 \dots a_{nd}x_d=b_n$$

The above system of linear equations can also be written down in a compact matrix form as follows:

$$AX = B$$

where,
$$A = \begin{bmatrix}
a_{11} & \dots & a_{1d}\\
\vdots & \ddots & \vdots \\
a_{n1} & \dots & a_{nd}
\end{bmatrix}, \quad
B = \begin{bmatrix}
b_1 \\ \vdots \\ b_n
\end{bmatrix}, \quad
X = \begin{bmatrix}
x_1 \\ \vdots \\ x_d
\end{bmatrix}.
$$

---
**Task 1.1**: Use numpy's solve function to compute X

---
**HINT**: https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html

In [4]:
# define A,B
A = np.array([[2, 0, 3], [1, -1, 2], [1, -3, 4]])
B = np.array([[2], [1], [2]])

def solve_with_numpy(A,B):
    ## YOUR CODE HERE
    return np.linalg.solve(A, B)

# show solution
X = solve_with_numpy(A,B)
print (X)

[[-0.5]
 [ 0.5]
 [ 1. ]]


A more hands on way for solving for X, involves computing first computing the inverse of the matrix $A$

---
**Task 1.2**: Use numpy's inbuilt method for computing the inverse of the matrix $A$

---

**HINT**: https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html

In [5]:
A = np.array([[-3, -2], [1, 1]])

A_inv = np.linalg.inv(A)  # YOUR CODE HERE
print(A_inv)

[[-1. -2.]
 [ 1.  3.]]


---
**Task 1.3**: Use the inverse of matrix $A$, to solve for $X$

---

In [6]:
A = np.array([[-3, -2], [1, 1]])
B = np.array([[4], [6]])

X = np.linalg.inv(A) @ B  # YOUR CODE HERE

print(X)

[[-16.]
 [ 22.]]


But what if $A$ is not a square matrix?

---
**Task 1.4**: Compute the Moore-Penrose pseudo inverse for matrix $A$ and use it for computing $X$. Note that, you must not directly use `np.linalg.pinv` for computing the pseudo-inverse.

---

**HINT**: https://en.wikipedia.org/wiki/Moore–Penrose_inverse

In [7]:
A = np.array([[1, 3], [2, 7], [5, 1]])
B = np.array([[13], [30], [9]])

A_pseudo_inverse = np.linalg.inv(A.T @ A) @ A.T  # YOUR CODE HERE
X = A_pseudo_inverse @ B  # YOUR CODE HERE

print(X)

[[1.]
 [4.]]


## Task 2: Solving a system of linear equations with Gaussian elimination

In the last task, we used numpy's inbulit functions to solve a system of linear equations. Lets do it without using these functions!

---
**Task 2.1**:  Complete the following gaussian elimnation function to compute the **reduced row-echelon form** of matrix $A$. You must implement the gaussian elimination algorithm yourself, not merely call someone else's library function. You **MUST NOT** copy codes from any source. Your function needs to work under **different shapes** of matrix. Negative zero is a result of the floating-point number standard. If you have some -0s instead of 0s, that should be fine.

---

In [8]:
from copy import deepcopy

def gaussian_elim(X):
    m, n = X.shape
    res = np.zeros((m, n))
    # YOUR CODE HERE
    res = deepcopy(X)
    print("---- Reducing to REF  ----")
    res = res.astype(float)  # keep floats instead of ints
    for i in range(min(m, n)):
        # check whether the row starts with zero
        swap_row = m - 1  # swap from the last bottom row
        # if so, do swapping untill the row starts with a non-zero
        # or we found the column is a zero vector
        while swap_row > i and res[i, i] == 0:
            print("swapping: r{} <-> r{}".format(i, swap_row))
            res[[swap_row, i]] = res[[i, swap_row]]
            swap_row -= 1
            print(res)
        if res[i, i] == 0:  # if we found the column is a zero vector
            continue  # jump to the next column
        # otherwise, the row now starts with a nonzero
        # whereas the bottom rows are expected to start with zeros

        # deliminate zeros in the rest of rows corresponding to the column
        for row in range(i + 1, m):
            print("deliminating: r{2} -> {0} * r{1} + r{2}".format(-(res[row, i] / res[i, i]), i, row))
            res[row, :] += -(res[row, i] / res[i, i]) * res[i, :]
            print(res)
    print("---- REF done ----\n")

    print("---- Reducing to RREF ----")
    # multiplication to make sure the leading variables are ones
    row, col = 0, 0
    while row < m and col < n:
        while col < n and res[row, col] == 0:  # if the diagonal variable in the row is zero
            col += 1  # the leading variable is on the right side of the diagonal variable
        if col == n:  # if no leading variable in the row, the RREF is done
            break
        if res[row, col] == 1:
            print("skip: r{}".format(row))
        else:
            print("deliminating: r{0} -> {1} * r{0}".format(row, 1 / res[row, col]))
            res[row] /= res[row, col]
        print(res)
        row += 1
        col += 1
    # bottom-up deliminate
    for i in range(m - 1, -1, -1):
        j = 0  # search the leading variable of the row
        while j < n and res[i, j] == 0:
            j += 1
        if j == n:  # if the row is a zero vector, jump to the row above
            continue
        for upper_row in range(i - 1, -1, -1):  # deliminating all rows above
            print("deliminating: r{0} -> {1} * r{2} + r{0}".format(upper_row, -res[upper_row, j], i))
            res[upper_row] += -res[upper_row, j] * res[i]
            print(res)
    print("---- REEF done ----\n")
    
    return res

In [9]:
A = np.array([[1, 0, 1, 1],
             [1, 0, 1, 1],
             [0, 1, 1, 1],
             [1, 1, 1, 0],
             [1, 1, 1, 0]], dtype=np.float64)
print(gaussian_elim(A))
#The result should look like
# [[ 1.,  0.,  0., -1.],
#  [ 0.,  1.,  0., -1.],
#  [-0., -0.,  1.,  2.],
#  [ 0.,  0.,  0.,  0.],
#  [ 0.,  0.,  0.,  0.]]

---- Reducing to REF  ----
deliminating: r1 -> -1.0 * r0 + r1
[[1. 0. 1. 1.]
 [0. 0. 0. 0.]
 [0. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]]
deliminating: r2 -> -0.0 * r0 + r2
[[1. 0. 1. 1.]
 [0. 0. 0. 0.]
 [0. 1. 1. 1.]
 [1. 1. 1. 0.]
 [1. 1. 1. 0.]]
deliminating: r3 -> -1.0 * r0 + r3
[[ 1.  0.  1.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  0. -1.]
 [ 1.  1.  1.  0.]]
deliminating: r4 -> -1.0 * r0 + r4
[[ 1.  0.  1.  1.]
 [ 0.  0.  0.  0.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  0. -1.]
 [ 0.  1.  0. -1.]]
swapping: r1 <-> r4
[[ 1.  0.  1.  1.]
 [ 0.  1.  0. -1.]
 [ 0.  1.  1.  1.]
 [ 0.  1.  0. -1.]
 [ 0.  0.  0.  0.]]
deliminating: r2 -> -1.0 * r1 + r2
[[ 1.  0.  1.  1.]
 [ 0.  1.  0. -1.]
 [ 0.  0.  1.  2.]
 [ 0.  1.  0. -1.]
 [ 0.  0.  0.  0.]]
deliminating: r3 -> -1.0 * r1 + r3
[[ 1.  0.  1.  1.]
 [ 0.  1.  0. -1.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
deliminating: r4 -> -0.0 * r1 + r4
[[ 1.  0.  1.  1.]
 [ 0.  1.  0. -1.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0.  0.]


In [10]:
B = np.array([[2, 0, 3, 1, 0, 2],
             [1, 3, 2, 0, 3, 1],
             [3, 2, 3, 1, 1, 2]])
print(gaussian_elim(B))
#The result should look like
# [[ 1.          0.          0.          0.36363636 -0.81818182  0.18181818]
#  [ 0.          1.          0.         -0.18181818  0.90909091 -0.09090909]
#  [ 0.          0.          1.          0.09090909  0.54545455  0.54545455]]

---- Reducing to REF  ----
deliminating: r1 -> -0.5 * r0 + r1
[[ 2.   0.   3.   1.   0.   2. ]
 [ 0.   3.   0.5 -0.5  3.   0. ]
 [ 3.   2.   3.   1.   1.   2. ]]
deliminating: r2 -> -1.5 * r0 + r2
[[ 2.   0.   3.   1.   0.   2. ]
 [ 0.   3.   0.5 -0.5  3.   0. ]
 [ 0.   2.  -1.5 -0.5  1.  -1. ]]
deliminating: r2 -> -0.6666666666666666 * r1 + r2
[[ 2.          0.          3.          1.          0.          2.        ]
 [ 0.          3.          0.5        -0.5         3.          0.        ]
 [ 0.          0.         -1.83333333 -0.16666667 -1.         -1.        ]]
---- REF done ----

---- Reducing to RREF ----
deliminating: r0 -> 0.5 * r0
[[ 1.          0.          1.5         0.5         0.          1.        ]
 [ 0.          3.          0.5        -0.5         3.          0.        ]
 [ 0.          0.         -1.83333333 -0.16666667 -1.         -1.        ]]
deliminating: r1 -> 0.3333333333333333 * r1
[[ 1.          0.          1.5         0.5         0.          1.        ]
 [ 0. 

We will evaluate your code with many different matrices. 

---
**Task 2.2**: A system of linear equations is called homogeneous if the right hand side is the zero vector. Sometimes there will be only trivial solution, namely the zero vector. An example of this matrix is:
$$2x_1+4x_2 =0$$
$$2x_1+5x_2 =0$$
Sometimes there will be non-trivial solutions, e.g.,
$$2x_1+4x_2 =0$$
$$1x_1+2x_2 =0$$
The solution can be $x_1 =-2$, $x_2 =1$.
 
$A=\big(\begin{smallmatrix}
  2 & 4\\
  1 & 2
\end{smallmatrix}\big)$ is called coefficient matrix.
Your task is solving a homogeneous system of linear equations based on its reduced row-echelon form, i.e., the output of your *gaussian_elim* function in Task 2.1. You **MUST NOT** revoke any numpy inbuilt functions you used in Task 1. Your function needs to work under **different shapes** of $A$. 

The *solve_homogeneous* function should be according to the following specifications:
* Take as input the coefficient matrix $A$. 
* Return:
    - 0 if it only has trivial solution. Type: int.
    - otherwise, return any two different non-trivial solutions. Type: tuple((np.ndarray, Type: np.ndarray)).  Note that the dimensions of the np.ndarray should be 1, i.e., using one pair of square brackets. See demo outputs below.

In [11]:
def solve_homogeneous(A):
    # YOUR CODE HERE
    A_rref = gaussian_elim(A)
    m, n = A_rref.shape
    res = [0 for _ in range(n)]
    
    row, col = 0, 0
    # search free variables
    while row < m and col < n:
        if A_rref[row][col] == 1:
            row += 1
            col += 1
            continue
        res[col] = 1  # set free variable to 1
        col += 1  # keep search from its left neighbor
    # check whether the last line has free variables
    # e.g. A = [[1, 0, 0], [0, 1, 2]], X_3 is a free varibale
    res[col:n] = [1] * (n - col)  
    if 1 in res:
        free_var = [i for i in range(len(res)) if res[i] == 1]
        print("index of free variable(s): {}\n".format(free_var))
    else:
        # if no free variable, return 0 directly
        print("no free variable\n")
        return 0
    
    leading_var_list = [i for i in range(len(res)) if res[i] == 0]
    for leading_var in leading_var_list:
        # suppose A_rref[leading_var, :] = [0, 1, 0, 2], res = [0, 0, 0, 1]
        # then X_2 + 2 * X_4 = 0, X_2 = -2 * X_4 = -2 * 1 = -2
        res[leading_var] = -1 * sum([A_rref[leading_var, i] * res[i] for i in range(n)])

    return (np.array(res), 2 * np.array(res))

In [12]:
A = np.array([[2, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], dtype=np.float64)
print(solve_homogeneous(A))
#The result should look like
# 0

---- Reducing to REF  ----
deliminating: r1 -> -2.0 * r0 + r1
[[2. 2. 3.]
 [0. 1. 0.]
 [7. 8. 9.]]
deliminating: r2 -> -3.5 * r0 + r2
[[ 2.   2.   3. ]
 [ 0.   1.   0. ]
 [ 0.   1.  -1.5]]
deliminating: r2 -> -1.0 * r1 + r2
[[ 2.   2.   3. ]
 [ 0.   1.   0. ]
 [ 0.   0.  -1.5]]
---- REF done ----

---- Reducing to RREF ----
deliminating: r0 -> 0.5 * r0
[[ 1.   1.   1.5]
 [ 0.   1.   0. ]
 [ 0.   0.  -1.5]]
skip: r1
[[ 1.   1.   1.5]
 [ 0.   1.   0. ]
 [ 0.   0.  -1.5]]
deliminating: r2 -> -0.6666666666666666 * r2
[[ 1.   1.   1.5]
 [ 0.   1.   0. ]
 [-0.  -0.   1. ]]
deliminating: r1 -> -0.0 * r2 + r1
[[ 1.   1.   1.5]
 [ 0.   1.   0. ]
 [-0.  -0.   1. ]]
deliminating: r0 -> -1.5 * r2 + r0
[[ 1.  1.  0.]
 [ 0.  1.  0.]
 [-0. -0.  1.]]
deliminating: r0 -> -1.0 * r1 + r0
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [-0. -0.  1.]]
---- REEF done ----

no free variable

0


In [13]:
B = np.array([[1, 2, 4],
              [1, 2, 4],
              [1, 8, 7]], dtype=np.float64)
print(solve_homogeneous(B))
#The result should look like
# (array([-3. , -0.5,  1. ]), array([-6., -1.,  2.]))

# Note that results are not unique

---- Reducing to REF  ----
deliminating: r1 -> -1.0 * r0 + r1
[[1. 2. 4.]
 [0. 0. 0.]
 [1. 8. 7.]]
deliminating: r2 -> -1.0 * r0 + r2
[[1. 2. 4.]
 [0. 0. 0.]
 [0. 6. 3.]]
swapping: r1 <-> r2
[[1. 2. 4.]
 [0. 6. 3.]
 [0. 0. 0.]]
deliminating: r2 -> -0.0 * r1 + r2
[[1. 2. 4.]
 [0. 6. 3.]
 [0. 0. 0.]]
---- REF done ----

---- Reducing to RREF ----
skip: r0
[[1. 2. 4.]
 [0. 6. 3.]
 [0. 0. 0.]]
deliminating: r1 -> 0.16666666666666666 * r1
[[1.  2.  4. ]
 [0.  1.  0.5]
 [0.  0.  0. ]]
deliminating: r0 -> -2.0 * r1 + r0
[[1.  0.  3. ]
 [0.  1.  0.5]
 [0.  0.  0. ]]
---- REEF done ----

index of free variable(s): [2]

(array([-3. , -0.5,  1. ]), array([-6., -1.,  2.]))


In [14]:
C = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=np.float64)
print(solve_homogeneous(C))
#The result should look like
# (array([ 1., -2.,  1.]), array([ 2., -4.,  2.]))

# Note that results are not unique

---- Reducing to REF  ----
deliminating: r1 -> -4.0 * r0 + r1
[[ 1.  2.  3.]
 [ 0. -3. -6.]]
---- REF done ----

---- Reducing to RREF ----
skip: r0
[[ 1.  2.  3.]
 [ 0. -3. -6.]]
deliminating: r1 -> -0.3333333333333333 * r1
[[ 1.  2.  3.]
 [-0.  1.  2.]]
deliminating: r0 -> -2.0 * r1 + r0
[[ 1.  0. -1.]
 [-0.  1.  2.]]
---- REEF done ----

index of free variable(s): [2]

(array([ 1., -2.,  1.]), array([ 2., -4.,  2.]))


In [15]:
D = np.array([[1, 2],
              [3, 4],
              [5, 6]], dtype=np.float64)
print(solve_homogeneous(D))
#The result should look like
# 0

---- Reducing to REF  ----
deliminating: r1 -> -3.0 * r0 + r1
[[ 1.  2.]
 [ 0. -2.]
 [ 5.  6.]]
deliminating: r2 -> -5.0 * r0 + r2
[[ 1.  2.]
 [ 0. -2.]
 [ 0. -4.]]
deliminating: r2 -> -2.0 * r1 + r2
[[ 1.  2.]
 [ 0. -2.]
 [ 0.  0.]]
---- REF done ----

---- Reducing to RREF ----
skip: r0
[[ 1.  2.]
 [ 0. -2.]
 [ 0.  0.]]
deliminating: r1 -> -0.5 * r1
[[ 1.  2.]
 [-0.  1.]
 [ 0.  0.]]
deliminating: r0 -> -2.0 * r1 + r0
[[ 1.  0.]
 [-0.  1.]
 [ 0.  0.]]
---- REEF done ----

no free variable

0


We will evaluate your code with many different matrices.

---
**Task 2.3**: A system of linear equations is called non-homogeneous if the right hand side is not the zero vector. A non-homogeneous system of linear equations has
* no solution, or
* a unique solution, or
* infinite number of solutions

Similar to Task 2.2, your task is solving a non-homogeneous system of linear equations. You **MUST NOT** revoke any numpy inbuilt functions you used in Task 1, however, you are allowed to use the functions you defined in Task 2.2. Your function needs to work under **different shapes** of augmented matrix $[A|b]$. 

The *solve_nonhomogeneous* function should be according to following specifications:
* Take as input the augmented matrix $[A|b]$. 
* Return:
    - None if it has no solution at all. Type: None.
    - the single solution if it only has one solution. Type: np.ndarray.
    - otherwise, return any two different solutions if it has more than one solutions. Type: tuple((np.ndarray, Type: np.ndarray)).
*  Note that the dimensions of the np.ndarray should be 1, especially, one pair of square brackets. See demo outputs below.    

In [16]:
def solve_nonhomogeneous(A_aug):
    # YOUR CODE HERE
    A_aug_rref = gaussian_elim(A_aug)
    A, b = A_aug_rref[:, :-1], A_aug_rref[:, -1]  # seperate the augumentation matrix
    m, n = A.shape
    res = [0 for _ in range(n)]
    
    row, col = 0, 0
    # search free variables
    while row < m and col < n:
        if A[row][col] == 1:
            row += 1
            col += 1
            continue
        res[col] = 1  # set free variable to 1
        col += 1  # keep search from its left neighbor
    # check whether the last line has free variables
    # e.g. A = [[1, 0, 0], [0, 1, 2]], X_3 is a free varibale
    res[col:n] = [1] * (n - col)  
    if 1 in res:
        free_var = [i for i in range(len(res)) if res[i] == 1]
        print("index of free variable(s): {}\n".format(free_var))
    else:
        # if no free variable, return b as the solution
        print("no free variable\n")
        return b
    
    leading_var_list = [i for i in range(len(res)) if res[i] == 0]
    n_leading_var = len(leading_var_list)
    for i in range(n_leading_var, m):
        if b[i] != 0:
            return None
    
    # deep copy, set the value of free varibales to 2 instead of 1
    res_2 = [2 * x for x in res]
    for leading_var in leading_var_list:
        # suppose A[1, :] = [0, 1, 0, 2], res = [0, 0, 0, 1], b = [0, 2, 0, 0]
        # then X_2 + 2 * X_4 = 2, X_2 = -2 * X_4 + 2= -2 * 1 + 2 = 0
        res[leading_var] = -1 * sum([A[leading_var, i] * res[i] for i in range(n)]) + b[leading_var]
        res_2[leading_var] = -1 * sum([A[leading_var, i] * res_2[i] for i in range(n)]) + b[leading_var]
        
        
    return (np.array(res), np.array(res_2))

In [17]:
A = np.array([
    [1, 2, 3, 1],
    [2, 4, 6, 3],
    [7, 8, 9, 4]
])
print(solve_nonhomogeneous(A))
#The result should look like
# None

---- Reducing to REF  ----
deliminating: r1 -> -2.0 * r0 + r1
[[1. 2. 3. 1.]
 [0. 0. 0. 1.]
 [7. 8. 9. 4.]]
deliminating: r2 -> -7.0 * r0 + r2
[[  1.   2.   3.   1.]
 [  0.   0.   0.   1.]
 [  0.  -6. -12.  -3.]]
swapping: r1 <-> r2
[[  1.   2.   3.   1.]
 [  0.  -6. -12.  -3.]
 [  0.   0.   0.   1.]]
deliminating: r2 -> 0.0 * r1 + r2
[[  1.   2.   3.   1.]
 [  0.  -6. -12.  -3.]
 [  0.   0.   0.   1.]]
---- REF done ----

---- Reducing to RREF ----
skip: r0
[[  1.   2.   3.   1.]
 [  0.  -6. -12.  -3.]
 [  0.   0.   0.   1.]]
deliminating: r1 -> -0.16666666666666666 * r1
[[ 1.   2.   3.   1. ]
 [-0.   1.   2.   0.5]
 [ 0.   0.   0.   1. ]]
skip: r2
[[ 1.   2.   3.   1. ]
 [-0.   1.   2.   0.5]
 [ 0.   0.   0.   1. ]]
deliminating: r1 -> -0.5 * r2 + r1
[[ 1.  2.  3.  1.]
 [-0.  1.  2.  0.]
 [ 0.  0.  0.  1.]]
deliminating: r0 -> -1.0 * r2 + r0
[[ 1.  2.  3.  0.]
 [-0.  1.  2.  0.]
 [ 0.  0.  0.  1.]]
deliminating: r0 -> -2.0 * r1 + r0
[[ 1.  0. -1.  0.]
 [-0.  1.  2.  0.]
 [ 0.  0.  0.

In [18]:
B = np.array([
    [1, 0, 1, 6],
    [0, -3, 1, 7],
    [2, 1, 3, 15]
])
print(solve_nonhomogeneous(B))
#The result should look like
# [ 2. -1.  4.]

---- Reducing to REF  ----
deliminating: r1 -> -0.0 * r0 + r1
[[ 1.  0.  1.  6.]
 [ 0. -3.  1.  7.]
 [ 2.  1.  3. 15.]]
deliminating: r2 -> -2.0 * r0 + r2
[[ 1.  0.  1.  6.]
 [ 0. -3.  1.  7.]
 [ 0.  1.  1.  3.]]
deliminating: r2 -> 0.3333333333333333 * r1 + r2
[[ 1.          0.          1.          6.        ]
 [ 0.         -3.          1.          7.        ]
 [ 0.          0.          1.33333333  5.33333333]]
---- REF done ----

---- Reducing to RREF ----
skip: r0
[[ 1.          0.          1.          6.        ]
 [ 0.         -3.          1.          7.        ]
 [ 0.          0.          1.33333333  5.33333333]]
deliminating: r1 -> -0.3333333333333333 * r1
[[ 1.          0.          1.          6.        ]
 [-0.          1.         -0.33333333 -2.33333333]
 [ 0.          0.          1.33333333  5.33333333]]
deliminating: r2 -> 0.75 * r2
[[ 1.          0.          1.          6.        ]
 [-0.          1.         -0.33333333 -2.33333333]
 [ 0.          0.          1.          4.  

In [19]:
C = np.array([
    [1, 2, 3, 1],
    [2, 4, 6, 2],
    [7, 8, 9, 4]
])
print(solve_nonhomogeneous(C))
#The result should look like
# (array([ 1. , -1.5,  1. ]), array([ 2. , -3.5,  2. ]))

---- Reducing to REF  ----
deliminating: r1 -> -2.0 * r0 + r1
[[1. 2. 3. 1.]
 [0. 0. 0. 0.]
 [7. 8. 9. 4.]]
deliminating: r2 -> -7.0 * r0 + r2
[[  1.   2.   3.   1.]
 [  0.   0.   0.   0.]
 [  0.  -6. -12.  -3.]]
swapping: r1 <-> r2
[[  1.   2.   3.   1.]
 [  0.  -6. -12.  -3.]
 [  0.   0.   0.   0.]]
deliminating: r2 -> 0.0 * r1 + r2
[[  1.   2.   3.   1.]
 [  0.  -6. -12.  -3.]
 [  0.   0.   0.   0.]]
---- REF done ----

---- Reducing to RREF ----
skip: r0
[[  1.   2.   3.   1.]
 [  0.  -6. -12.  -3.]
 [  0.   0.   0.   0.]]
deliminating: r1 -> -0.16666666666666666 * r1
[[ 1.   2.   3.   1. ]
 [-0.   1.   2.   0.5]
 [ 0.   0.   0.   0. ]]
deliminating: r0 -> -2.0 * r1 + r0
[[ 1.   0.  -1.   0. ]
 [-0.   1.   2.   0.5]
 [ 0.   0.   0.   0. ]]
---- REEF done ----

index of free variable(s): [2]

(array([ 1. , -1.5,  1. ]), array([ 2. , -3.5,  2. ]))


We will evaluate your code with many different matrices.

## Task 3: Gram-Schmidt orthogonalization

The Gram-Schmidt algorithm is used for finding an orthonormal basis for the subspace spanned by a set of vectors.

Given a linearly independent set of vectors $S = \lbrace \mathbf{v_1}, \mathbf{v_2}, ..., \mathbf{v_n} \rbrace$, an orthogonal set $S' = \lbrace \mathbf{u_1}, \mathbf{u_2}, ..., \mathbf{u_n} \rbrace $ can be generated under this procedure:


$\mathbf{u_1} = \mathbf{v_1}$\
$\mathbf{u_2} = \mathbf{v_2} - \textrm{proj}_{\mathbf{u_1}}(\mathbf{v_2})$\
$\mathbf{u_3} = \mathbf{v_3} - \textrm{proj}_{\mathbf{u_1}}(\mathbf{v_3}) - \textrm{proj}_{\mathbf{u_2}}(\mathbf{v_3})$\
...\
$\mathbf{u_n} = \mathbf{v_n} - \sum_{i=1}^{n-1}\textrm{proj}_{\mathbf{u_i}}(\mathbf{v_n})$,

where $\textrm{proj}_{\mathbf{u}}(\mathbf{v}) = \dfrac{\langle \mathbf{u}, \mathbf{v} \rangle}{\langle \mathbf{u}, \mathbf{u} \rangle}\mathbf{u}$

The orthogonal set is not normalized, you can normalize it by $\mathbf{e_i} = \dfrac{\mathbf{u_i}}{||\mathbf{u_i}||}$

---
**Read more:** https://en.wikipedia.org/wiki/Gram–Schmidt_process

---
**Task 3.1**: Implement a function that finds an orthonormal basis of row vectors for matrix $A$. The *gram_schmidt* function should be according to following specifications: 
* Take as input any matrix $A$.
* Return a matrix with the orthonormal basis vectors as the rows.

---
**NOTE**: The resulting basis should be orthonormal, so each basis vector should be of norm 1.

In [20]:
# Find orthonormal basis using gram-schmidt 
def gram_schmidt(A):
    # YOUR CODE HERE
    
    m, n = A.shape
    A_orthogonal = []
    A_normalized_orthogonal = []
    
    for row_A in range(m):
        orthogonal = np.array(A[row_A])  # the vector to be transformed
        print("original row {}: {}".format(row_A, A[row_A]))
        
        # Gram-Schmidt orthogonalization
        for row_A_orthogonal in range(row_A):
            denominator_inner_prod = A[row_A] @ A_orthogonal[row_A_orthogonal].T  # <v, u>
            numerator_inner_prod = A_orthogonal[row_A_orthogonal] @  A_orthogonal[row_A_orthogonal].T  # <u, u>
            # cumulatively subtract Proj_u_j(v_i)， where j = {1, 2, 3, ..., v_(i-1)}
            orthogonal = orthogonal - (denominator_inner_prod / numerator_inner_prod) * A_orthogonal[row_A_orthogonal]
        A_orthogonal.append(orthogonal)
        print("orthogonal row {}: {}".format(row_A, A_orthogonal[row_A]))
        
        # check whether the orthogonal vector is a zero vector
        if orthogonal @ orthogonal.T > 0:  # if not, normalize the vector
            orthogonal_normalized = orthogonal / pow(orthogonal @ orthogonal.T, 0.5)  
            A_normalized_orthogonal.append(orthogonal_normalized)
            print("normalized orthogonal row {}: {}\n".format(row_A, A_normalized_orthogonal[row_A]))
        else:
            print("invalid normalized orthogonal row {}\n".format(row_A))
        
    
    return np.array([list(row) for row in A_normalized_orthogonal])

In [21]:
A = np.array([[0, -1, 2, 0, 2],
              [1, -3, 1, -1, 2],
              [-3, 4, 1, 2, 1],
              [-1, -3, 5, 0, 7]])

print(gram_schmidt(A))

#The result should look like
# [[ 0.         -0.33333333  0.66666667  0.          0.66666667]
#  [ 0.37796447 -0.75592895 -0.37796447 -0.37796447  0.        ]
#  [-0.57735027  0.         -0.57735027  0.          0.57735027]]

original row 0: [ 0 -1  2  0  2]
orthogonal row 0: [ 0 -1  2  0  2]
normalized orthogonal row 0: [ 0.         -0.33333333  0.66666667  0.          0.66666667]

original row 1: [ 1 -3  1 -1  2]
orthogonal row 1: [ 1. -2. -1. -1.  0.]
normalized orthogonal row 1: [ 0.37796447 -0.75592895 -0.37796447 -0.37796447  0.        ]

original row 2: [-3  4  1  2  1]
orthogonal row 2: [-1.  0. -1.  0.  1.]
normalized orthogonal row 2: [-0.57735027  0.         -0.57735027  0.          0.57735027]

original row 3: [-1 -3  5  0  7]
orthogonal row 3: [0. 0. 0. 0. 0.]
invalid normalized orthogonal row 3

[[ 0.         -0.33333333  0.66666667  0.          0.66666667]
 [ 0.37796447 -0.75592895 -0.37796447 -0.37796447  0.        ]
 [-0.57735027  0.         -0.57735027  0.          0.57735027]]


We will evaluate your code with many different matrices.

---
**TASK 3.2:** Implement a function that accepts a matrix and returns TRUE if all the rows of that matrix are orthogonal to one another, and each one of them is of length 1. Use this function to verify the output of your *gram_schmidt* function is actually correct. Again, you must program this function yourself, rather than relying on a library function.

You can check whether your algorithms work using the last 6 lines in the code given below.

In [22]:
def orthogonality_checker(A):
    # YOUR CODE HERE
    
    m, n = A.shape
    threshold = 10e-6
    # check whether the length equals to 1
    for row in range(m):
        row_length = pow(A[row] @ A[row].T, 0.5)
        if abs(row_length - 1) > threshold:
            print("the length of row {} ({}) does not equal to 1".format(row, row_length))
            return False
    print("all rows are have length 1")
       
    for row_i in range(m):
        for row_j in range(row_i + 1, m):
            if A[row_i] @ A[row_j] != 0:
                print("row {} and row {} are not orthogonal".format(row_i, row_j))
                return False
    print("all rows are orthogonal with others")
    
    return True
    

true_test = np.eye(3,3)
false_test = np.ones((3,3))
print('\nCHECKING TRUE TEST (SHOULD RETURN TRUE):')
print(orthogonality_checker(true_test))
print('\nCHECKING FALSE TEST (SHOULD RETURN FALSE):')
print(orthogonality_checker(false_test))


CHECKING TRUE TEST (SHOULD RETURN TRUE):
all rows are have length 1
all rows are orthogonal with others
True

CHECKING FALSE TEST (SHOULD RETURN FALSE):
the length of row 0 (1.7320508075688772) does not equal to 1
False


We will evaluate your code with many different matrices.