**COMP3670/6670 Assignment 5**
---

**Enter Your Student ID:**

**Your Name:** 
    
**Deadline:** N.A

**Submit:** N.A
    
**Enter Discussion Partner IDs Below:**
- <Enter ID 1>
- <Enter ID 2>
- <Enter ID 3>

**Programming Section** (100%)
- 1.1 = 5%
- 1.2 = 5%
- 1.3 = 10%
- 1.4 = 15%
- 1.5 = 5%
- 1.6 = 10%
- 2.1 = 50%


THEORY SECTION (0%)
---

There are no theory questions.

---


**PROGRAMMING SECTION (100%)**
---

For all of the following, program the solution yourself. Don't just call a library function that does the whole question for you, or you'll get zero (no, that doesn't mean you can't use any library functions, but it does mean that you have to show you understand how to compute the answer yourself).

**All written answers** should be between 50 and 500 words. If you can describe all the necessary information in 50 words, that's better. However, you'll only be graded on whether you describe the necessary ideas.


-----------

   **TASK 0.1:** You know the drill. Import Numpy and PyPlot. We're also going to generate a dataset.


-----------

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D #This is for 3d scatter plots.
import math
import random
from scipy.stats import multivariate_normal
import os
from matplotlib.pyplot import imread
np.random.seed(13579201)

k = 4
n = 8
m = 5000
D = np.zeros((m, n))
Y = np.zeros((m, k))
for ix in range(0, m):
    dpool = random.randint(0, 2**n)
    ypool = round(np.sqrt(dpool))
    for iy in range(n):
        if dpool >= 2**(D.shape[1] - iy - 1):
            D[ix, iy] = 1
            dpool -= 2**(D.shape[1] - iy - 1)
    for iy in range(Y.shape[1]):
        if ypool >= 2**(Y.shape[1] - iy - 1):
            reading = ((np.random.randn() + 0.3) > 0)
            Y[ix, iy - k] = 1 * reading
            ypool -= 2**(Y.shape[1] - iy - 1)

print(D)
print(Y)
print('Done')

[[0. 0. 1. ... 1. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [1. 1. 1. ... 0. 0. 1.]
 ...
 [1. 1. 1. ... 1. 1. 0.]
 [0. 0. 1. ... 1. 0. 1.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 1. 0. 0.]
 ...
 [1. 1. 1. 1.]
 [0. 1. 0. 1.]
 [0. 0. 0. 0.]]
Done


PROGRAMMING EXERCISE 1  
-----------

Note that for all of the questions that follow, you may re-use any code from your previous assignments.

We're going to implement logistic regression with gradient descent in this first exercise.

It's much like linear regression, but we apply a sigmoid function to the output, which of course changes the gradient!

The point of logistic regression is to predict a label {0, 1} or a probability.

We're going to re-use the dataset from assignment 5 for this problem:

$D \in \mathbb{R}^{m \times n}$ together with $Y \in \mathbb{R}^{m \times k}$ is our dataset.

Our objective is to predict $Y$ given $D$, such that $s(D\theta) = Y$, where $s()$ is the same logistic or sigmoid function you used in assignment 4.

We're going to use logistic regression to predict a binary string!


---
   **TASK 1.1:** Complete the function $initialise(D, Y) = \theta$, which detects the dimensions of $D$ and $Y$ and generates $\theta$ of appropriate dimension, with random values appropriate for regression, such that the dimensions of $D\theta$ is the same as the dimensions of $Y$.

---


In [ ]:
def initialise(D, Y):
    theta = None
    #YOUR CODE HERE
    return theta

theta = initialise(D, Y)
print(theta)


---

**TASK 1.2:** Complete $s(Z) = sZ$, which accepts a matrix $Z$ and outputs $sZ$, where $sZ$ is just $Z$ with the sigmoid (or "logistic") function applied to every element.

You must do this without using a loop.

**HINT:** 
- Recall assignment 4, where you applied the sigmoid function in exactly the same manner.
- You might want to use np.vectorize(). You'll probably need to define a second function which accepts a single element and applies the sigmoid function to that element (this is how np.vectorize works).

---


In [ ]:
def s(Z):
    sZ = None
    #YOUR CODE HERE
    return sZ

print((s(D@theta * 999999999)).astype('int'))

Recall assignment 4, where you implemented a neural network where the $X\theta^{[1]}$ had a sigmoid function applied to its output.

Thus the first layer was the function $s(X\theta^{[1]})$.

That first layer was performing logistic regression with mean squared error!

Now, for what follows you may choose any convex loss function you wish. For instance, you might:

1. Implement the mean squared loss function as you did in assignment 4 exercise 2 (this will only get you half marks).
2. Implement the cross-entropy loss (this is the most common loss function for logistic regression, and I recommend you implement this).
3. Implement anything else your heart desires, so long as it functions as a convex loss function for logistic regression!

Not sure what convex is? Then you must look this up. Convex means the loss function has only one global minimum!

Likewise with cross entropy loss; you need to research and understand this on your own. 

Cross entropy loss when $k = 1$ is computed as follows:

$\mathcal{L}(\theta) = -\frac{1}{m}\sum_{i=0}^m \left[y_i ln (s(d_i\theta)) + (1 - y_i) ln (1 - s(d_i\theta))\right] + \frac{\gamma}{2}\theta^T\theta$

... where $ln(z)$ is the natural logarithm of a scalar $z$.

When $k =1$, $s(d_i\theta)$ and $y_i$ are scalars. As $k > 1$, you'll need to modify the above loss function to work with vectors.

---

**TASK 1.3:** Complete the function $\mathcal{L}(\theta) = loss(D, \theta, Y) = l$, where $l$ is a scalar that represents the loss. That means $l$ is the sum of the $k$ losses (because we're simultaneously running $k$ regressions again).

You will get 50% for implementing the mean squared loss function you used in assignment 4 exercise 2, or 100% for implementing a different loss function (so long as it works).

Bear in mind you will need to compute $\frac{d \mathcal{L}(\theta)}{d \theta}$ for this loss function in order to complete the next question, so pick something you actually know how to compute the derivative of.

You must also include a form of regularisation such as $\gamma \theta^T \theta$, where $\gamma$ is a scalar chosen by you (I suggest something like 0.0001). When computing regularisation, remember that $k > 1$. 20% of your grade will be deducted for failing to implement a form of regularisation.

**HINT:** If implementing cross entropy loss, you'll need to account for taking the log of $0$.

---

In [ ]:
def loss(D, theta, Y):
    l = None
    #YOUR CODE HERE
    return l

l = loss(D, theta, Y)
print(l)

---

**TASK 1.4:** Implement $gradient\_update(D, \theta, Y, \lambda) = \theta - \lambda \frac{d \mathcal{L}(\theta)}{d \theta} = \theta_{new}$, which updates $\theta$ using the gradient of the loss function you implemented above.

It must be the gradient of the loss function you implemented, not a different loss function.

$\lambda$ is the learning rate.

As above, if it's just the mean squared loss you will only be eligible for 50% of the grade, and 20% of your grade will be deducted for not including a form of regularisation.

---

In [ ]:
def gradient_update(D, theta, Y, lam):
    theta_new = None
    #YOUR CODE HERE
    return theta_new

theta_new_test = gradient_update(D, theta, Y, 0.05)
print(theta_new_test)

---

**TASK 1.5:** Complete the function $predict(d, \theta) = s(d\theta) = y$, where $y \in \{0, 1\}^{(p \times k)}$ and $d \in \{0, 1\}^{(p \times n)}$ and $1 \ge p \ge m$.

Note, every element of the output must be an integer.

---

In [ ]:
def predict(d, theta):
    y = None
    #YOUR CODE HERE
    return y

print(predict(D[0:7, :], theta))

---

**TASK 1.6:** Complete the function $gradient\_descent(D, Y, lam, iterations) = \theta$, which  uses the functions above to find $\theta$ such that $predict(D, \theta) = Y$.

As in assignment 4, record the loss at each iteration and store the values in the array $losses$.

You need to make sure your loss decreases in monotone downward trajectory. If it increases at any point, something has gone wrong.

You will be assessed on whether, overall, you've succeeded in implementing logistic regression (not just the gradient descent algorithm, which you've done before in any case).

**HINT:** 
- Remember, at the start of this assignment we said you could re-use your code from previous assignments.
- Also, it's impossible to get zero error. You need to just minimise the error.

---

In [ ]:
def gradient_descent(D, Y, lam, iterations):
    theta = initialise(D, Y)
    losses = np.zeros((iterations))
    #YOUR CODE HERE
    return theta, losses

lam = 0.3 #Learning rate
iterations = 60 #Number of iterations of gradient descent

#For the purposes of doing this assignment, this code isn't really here. Pretend it's engraved in rock.
theta, losses = gradient_descent(D, Y, lam, iterations)
plt.plot(losses)
plt.show()
print(theta)