## COMP3670 Programming Assignment 1 - Linear Algebra and Analytic Geometry
---

**Enter Your Student ID:** 

**Your Name:**
    
**Deadline:**

**Submit:** Write your answers in this file, and submit a single Jupyter Notebook file (.ipynb) on Wattle. Rename this file with your student number as 'uXXXXXXX.ipynb'.

**Enter Discussion Partner IDs Below:**
You could add more IDs with the same markdown format above.



---
**Marking distribution for the assignment**

- Task1 = 10%
- Task2 = 50%
- Task3 = 40%

**You will get full marks if your program passes all the tests; you will get partial marks if it passes some cases. There is no process marks (we do not look into your codes).**

## Task 0: Introduction
---

**NOTE:** *This part of the first assignment is by necessity somewhat tedious as its primary purpose is to introduce syntax, how to access and understand the Numpy documentation and some very basic concepts. If you are already familiar with Numpy, you can just read the **TASK** headings and complete the questions without worrying about all the additional information. This is designed for people who have never seen Numpy before, so it's a very easy 1st year style introduction to just introduce syntax.*

*As this is a third year subject, it is assumed you already know to to program well (but may be unfamiliar with Python and Numpy).*

---

Arguably the most fundamental tool needed to engage with machine learning in Python is Numpy *(np)*. To include Numpy in any project, simply type the following line at the top of your python file:

In [1]:
# numpy
import numpy as np

!pip install sympy
import sympy as sp

# matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

A Jupyter Notebook is divided into cells, each of which works like a Python module or Latex file. When a cell is run, any cells that follow it will have access to its results. Running the above cell will give all following cells access to the Numpy library.

-----------

   **TASK 0.1:** To run the above cell, select it by clicking on it, hold **shift** and press **return**. If you have succeeded, then the cell will print "Done" just above.


-----------

Numpy is a library of common mathematical data structures and algorithms used in machine learning. For example:

- It allows you to declare vectors and matrices, with all the associated mathematical operations like matrix vector products, matrix addition / subtraction.
- It provides convenient, efficient implementations of algorithms to solve matrix equations, find the inverse of a matrix or perform Eigen decomposition. The implementation of these algorithms is compiled from C code, making Numpy much faster than programming these algorithms yourself in Python.

You'll need to know Numpy inside and out. We'll start by getting you familiar with the easy to access online documentation and performing a few basic operations.

Below I have declared the matrices: 

$$A = 
\begin{bmatrix}
2&3\\
0&1\\
\end{bmatrix}
\\
x = 
\begin{bmatrix}
1\\
3\\
\end{bmatrix}
$$. 

---
**TASK 0.2:** Run the cell below and observe what it prints.


---
(If it throws an error, you have the wrong version of python installed. This entire course will use Python 3, not Python 2)



In [2]:
A = np.array([[2, 3], [0, 1]])
x = np.array([[1], [3]])

#Matrix Multiplication Example
b = A @ x
print('\nMatrix Multiplication')
print(b)


Matrix Multiplication
[[11]
 [ 3]]


The above code illustrates how to perform matrix multiplication. Memorise it. Below are some other basic operations you'll likely need over the coming semester:

In [3]:
#Matrix Addition Example
b = A + x
print('\nMatrix Addition')
print(b)

#Elementwise Multiplication Example
b = A * x
print('\nElementwise Matrix Multiplication')
print(b)

#Extract a single element of a matrix:
print('\nSingle Element Extraction')
b = A[0, 0]
print(b)

#Extract an entire column of a matrix:
print('\nColumn Extraction')
b = A[:, 0]
print(b)

#Extract an entire row of a matrix:
print('\nRow Extraction')
b = A[0, :]
print(b)

#Transpose of a matrix:
print('\nTranspose')
A_Transpose = A.T
print(A_Transpose)


Matrix Addition
[[3 4]
 [3 4]]

Elementwise Matrix Multiplication
[[2 3]
 [0 3]]

Single Element Extraction
2

Column Extraction
[2 0]

Row Extraction
[2 3]

Transpose
[[2 0]
 [3 1]]


## Task1: Solving a system of linear equations
---

A vital part of linear algebra is to know how to solve a system of linear equations. For e.g. 

$$a_{11}x_1+a_{12}x_2 \dots a_{1d}x_d=b_1$$
$$a_{21}x_1+a_{22}x_2 \dots a_{2d}x_d=b_2$$
$$\vdots$$
$$a_{n1}x_1+a_{n2}x_2 \dots a_{nd}x_d=b_n$$

The above system of linear equations can also be written down in a compact matrix form as follows:

$$AX = B$$

where,
$$A = \begin{bmatrix}
a_{11} & \dots & a_{1d}\\
\vdots & \ddots & \vdots \\
a_{n1} & \dots & a_{nd}
\end{bmatrix}, \quad
B = \begin{bmatrix}
b_1 \\ \vdots \\ b_n
\end{bmatrix}, \quad
X = \begin{bmatrix}
x_1 \\ \vdots \\ x_d
\end{bmatrix}.
$$

---
**Task 1.1**: Use numpy's solve function to compute X

---
**HINT**: https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.solve.html

In [4]:
# define A,B
A = np.array([[2, 0, 3], [1, -1, 2], [1, -3, 4]])
B = np.array([[2], [1], [2]])

def solve_with_numpy(A,B):
    return np.linalg.solve(A, B)

# show solution
X = solve_with_numpy(A,B)
print (X)

[[-0.5]
 [ 0.5]
 [ 1. ]]


A more hands on way for solving for X, involves computing first computing the inverse of the matrix $A$

---
**Task 1.2**: Use numpy's inbuilt method for computing the inverse of the matrix $A$

---

**HINT**: https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html

In [5]:
A = np.array([[-3, -2], [1, 1]])

A_inv = np.linalg.inv(A)
print(A_inv)

[[-1. -2.]
 [ 1.  3.]]


---
**Task 1.3**: Use the inverse of matrix $A$, to solve for $X$

---

In [6]:
A = np.array([[-3, -2], [1, 1]])
B = np.array([[4], [6]])

X = np.linalg.inv(A)@B

print(X)

[[-16.]
 [ 22.]]


But what if $A$ is not a square matrix?

---
**Task 1.4**: Compute the Moore-Penrose pseudo inverse for matrix $A$ and use it for computing $X$. Note that, you must not directly use `np.linalg.pinv` for computing the pseudo-inverse.

---

**HINT**: https://en.wikipedia.org/wiki/Moore–Penrose_inverse

In [7]:
A = np.array([[1, 3], [2, 7], [5, 1]])
B = np.array([[13], [30], [9]])

A_pseudo_inverse = np.linalg.inv(A.T@A)@A.T
X =  A_pseudo_inverse@B

print(A_pseudo_inverse)
print(X)

[[-0.00544323 -0.02799378  0.21228616]
 [ 0.05287714  0.12908243 -0.0622084 ]]
[[1.]
 [4.]]


## Task 2: Solving a system of linear equations with Gaussian elimination

In the last task, we used numpy's inbulit functions to solve a system of linear equations. Lets do it without using these functions!

---
**Task 2.1**:  Complete the following gaussian elimnation function to compute the **reduced row-echelon form** of matrix $A$. You must implement the gaussian elimination algorithm yourself, not merely call someone else's library function. You **MUST NOT** copy codes from any source. Your function needs to work under **different shapes** of matrix. Negative zero is a result of the floating-point number standard. If you have some -0s instead of 0s, that should be fine.

---

In [8]:
def gaussian_elim(X):
    m, n = X.shape
    res = np.array(X, dtype=np.float64)
    h = 0
    k = 0
    lead = 0
    while h < res.shape[0] and k < res.shape[1]:
        i_max = np.argmax(np.abs(res[h:, k])) + h
        if abs(res[i_max][k]) < 1e-10:
            k += 1
        else:
            tmp = np.copy(res[h])
            res[h] = res[i_max]
            res[i_max] = tmp
            for i in range(h + 1, res.shape[0]):
                f = res[i][k] / res[h][k]
                res[i][k] = 0
                res[i][k + 1:] -= res[h][k + 1:] * f
            h += 1
            k += 1
            lead += 1
    while lead > 0:
        h = lead - 1
        for i in range(0, res.shape[1]):
            if abs(res[h][i]) > 1e-10:
                pivot = res[h][i]
                pivot_arg = i
                break
        res[h] = res[h] / pivot
        for i in range(0, h):
            f = res[i][pivot_arg]
            res[i] = res[i] - f * res[h]
        lead -= 1
    res[abs(res) < 1e-10] = 0
    return res

In [9]:
A = np.array([[1, 0, 1, 1],
             [1, 0, 1, 1],
             [0, 1, 1, 1],
             [1, 1, 1, 0],
             [1, 1, 1, 0]], dtype=np.float64)
print(gaussian_elim(A))
#The result should look like
# [[ 1.,  0.,  0., -1.],
#  [ 0.,  1.,  0., -1.],
#  [-0., -0.,  1.,  2.],
#  [ 0.,  0.,  0.,  0.],
#  [ 0.,  0.,  0.,  0.]]

[[ 1.  0.  0. -1.]
 [ 0.  1.  0. -1.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [10]:
B = np.array([[2, 0, 3, 1, 0, 2],
             [1, 3, 2, 0, 3, 1],
             [3, 2, 3, 1, 1, 2]])
print(gaussian_elim(B))
#The result should look like
# [[ 1.          0.          0.          0.36363636 -0.81818182  0.18181818]
#  [ 0.          1.          0.         -0.18181818  0.90909091 -0.09090909]
#  [ 0.          0.          1.          0.09090909  0.54545455  0.54545455]]

[[ 1.          0.          0.          0.36363636 -0.81818182  0.18181818]
 [ 0.          1.          0.         -0.18181818  0.90909091 -0.09090909]
 [ 0.          0.          1.          0.09090909  0.54545455  0.54545455]]


We will evaluate your code with many different matrices.

In [11]:
# test your gaussian_elim function
def test_gaussian_elim():
    for i in range(100):
        m, n = np.random.randint(low=5, high=10, size=2)
        a = np.random.randn(m, n)
        sol1 = gaussian_elim(a)
        sol2 = np.array(sp.Matrix(a).rref()[0])
        if np.sum((sol1 - sol2) ** 2) > 1e-6:
            print(a, "\n")
            print(gaussian_elim(a), "\n")
            print(np.array(sp.Matrix(a).rref()[0]), "\n")
            return False
    test_cases = [np.array([[2, 0, 1, 1],
                            [2, 0, 1, 1],
                            [0, 0, 0, 0],
                            [1, 1, 1, 0]], dtype=np.float64),
                  np.array([[1, 2, 3],
                            [4, 5, 6],
                            [7, 8, 9]], dtype=np.float64),
                  ]
    for test in test_cases:
        sol1 = gaussian_elim(test)
        sol2 = np.array(sp.Matrix(test).rref()[0])
        if np.sum((sol1 - sol2) ** 2) > 1e-6:
            print(test, "\n")
            print(gaussian_elim(test), "\n")
            print(np.array(sp.Matrix(test).rref()[0]), "\n")
            return False
    return True
test_gaussian_elim()

True

---
**Task 2.2**: A system of linear equations is called homogeneous if the right hand side is the zero vector. Sometimes there will be only trivial solution, namely the zero vector. An example of this matrix is:
$$2x_1+4x_2 =0$$
$$2x_1+5x_2 =0$$
Sometimes there will be non-trivial solutions, e.g.,
$$2x_1+4x_2 =0$$
$$1x_1+2x_2 =0$$
The solution can be $x_1 =-2$, $x_2 =1$.
 
$A=\big(\begin{smallmatrix}
  2 & 4\\
  1 & 2
\end{smallmatrix}\big)$ is called coefficient matrix.
Your task is solving a homogeneous system of linear equations based on its reduced row-echelon form, i.e., the output of your *gaussian_elim* function in Task 2.1. You **MUST NOT** revoke any numpy inbuilt functions you used in Task 1. Your function needs to work under **different shapes** of $A$. 

The *solve_homogeneous* function should be according to the following specifications:
* Take as input the coefficient matrix $A$. 
* Return:
    - 0 if it only has trivial solution. Type: int.
    - otherwise, return any two different non-trivial solutions. Type: tuple((np.ndarray, Type: np.ndarray)).  Note that the dimensions of the np.ndarray should be 1, i.e., using one pair of square brackets. See demo outputs below.

In [12]:
def find_pivot_pos(rref, m, n):
    pivot_pos = []
    for i in range(m):
        pos = np.where(rref[i] == 1)[0]
        if len(pos) > 0:
            pivot_pos.append(pos[0])
    free_var_pos = [p for p in range(n - 1) if p not in pivot_pos]
    return pivot_pos, free_var_pos


# solve homogeneous or non-homogeneous system of equations when they have one or more solutions
def solve(rref):
    m, n = rref.shape
    pivot_pos, free_var_pos = find_pivot_pos(rref, m, n)
    res = [[0 for _ in range(n - len(pivot_pos))] for _ in range(n - 1)]
    i = 0
    while i <= m - 1:
        j = 0
        while j <= n - 2:
            if rref[i, j] == 1 and j in pivot_pos:
                pj = j
                res[j][0] = rref[i, n - 1]
            if rref[i, j] != 0 and j not in pivot_pos:
                k = free_var_pos.index(j) + 1
                res[pj][k] = -rref[i, j]
            j += 1
        i += 1
    k = 1
    j = 0
    while j <= n - 2:
        if j in free_var_pos:
            res[j][k] = 1
            k += 1
        j += 1
    return np.array(res)

In [13]:
def solve_homogeneous(A):
    # YOUR CODE HERE
    m, n = A.shape
    rref = gaussian_elim(A)
    rank = 0
    for i in range(m):
        if np.any(rref[i]):
            rank += 1
    if rank == n:
        return 0
    else:
        rref = np.column_stack((rref, np.zeros(m)))
        res = solve(rref)
        return np.sum(res, axis=1), 2 * np.sum(res, axis=1)

In [14]:
A = np.array([[2, 2, 3],
              [4, 5, 6],
              [7, 8, 9]], dtype=np.float64)
print(solve_homogeneous(A))
#The result should look like
# 0

0


In [15]:
B = np.array([[1, 2, 4],
              [1, 2, 4],
              [1, 8, 7]], dtype=np.float64)
print(solve_homogeneous(B))
#The result should look like
# (array([-3. , -0.5,  1. ]), array([-6., -1.,  2.]))

# Note that results are not unique

(array([-3. , -0.5,  1. ]), array([-6., -1.,  2.]))


In [16]:
C = np.array([[1, 2, 3],
              [4, 5, 6]], dtype=np.float64)
print(solve_homogeneous(C))
#The result should look like
# (array([ 1., -2.,  1.]), array([ 2., -4.,  2.]))

# Note that results are not unique

(array([ 1., -2.,  1.]), array([ 2., -4.,  2.]))


In [17]:
D = np.array([[1, 2],
              [3, 4],
              [5, 6]], dtype=np.float64)
print(solve_homogeneous(D))
#The result should look like
# 0

0


We will evaluate your code with many different matrices.

In [18]:
def test_homogeneous_trivial():
    # test A with m>n and m=n but no dependent rows in it
    for i in range(1000):
        m = np.random.randint(low=4, high=6)
        n = np.random.randint(low=2, high=5)
        a = np.random.randn(m, n)
        res = solve_homogeneous(a)
        if res != 0:
            print(a, '\n')
            print(f' solution should be 0 but got {res}')
            return False
    # test A with m>n and there are dependent rows in it
    test_list = [
        np.array([[1, 2], [3, 4], [2, 4]]),
        np.array([[1, 2, 3], [2, 4, 6], [3, 4, 5], [4, 7, 9]]),
    ]
    for case in test_list:
        res = solve_homogeneous(case)
        if res != 0:
            print(a, '\n')
            print(f' solution should be 0 but got {res}')
            return False
    return True

def test_homogeneous_nontrivial():
    import random
    # test A with m=n and m<n
    for i in range(1000):
        m = np.random.randint(low=2, high=5)
        n = np.random.randint(low=4, high=6)
        a = np.random.randn(m, n)
        a_ = a.copy()
        # create matrices whose rows or columns are dependent
        dpdt = random.sample(range(0, m), np.random.randint(low=2, high=m + 1))
        duplicate = a[dpdt[0]]
        for row in dpdt:
            a[row] = duplicate
        x1 = np.expand_dims(solve_homogeneous(a)[0], axis=1)
        x2 = np.expand_dims(solve_homogeneous(a)[1], axis=1)
        if abs(np.sum(a @ x1)) > 1e-6 or abs(np.sum(a @ x2)) > 1e-6 or (x1==x2).all():
            print(a_, '\n')
            print('the solutions are not correct')
            return False
    # test A with m>n
    test_list = [
        np.array([[1, 2], [1, 2], [2, 4]]),
        np.array([[1, 2, 3], [3, 6, 9], [1, 2, 3], [4, 7, 9]]),
        np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    ]
    for case in test_list:
        x1 = np.expand_dims(solve_homogeneous(case)[0], axis=1)
        x2 = np.expand_dims(solve_homogeneous(case)[1], axis=1)
        if abs(np.sum(case @ x1)) > 1e-6 or abs(np.sum(case @ x2)) > 1e-6 or (x1==x2).all():
            print(a_, '\n')
            print('the solutions are not correct')
            return False
    return True

print(test_homogeneous_trivial())
print(test_homogeneous_nontrivial())

True
True


---
**Task 2.3**: A system of linear equations is called non-homogeneous if the right hand side is not the zero vector. A non-homogeneous system of linear equations has
* no solution, or
* a unique solution, or
* infinite number of solutions

Similar to Task 2.2, your task is solving a non-homogeneous system of linear equations. You **MUST NOT** revoke any numpy inbuilt functions you used in Task 1, however, you are allowed to use the functions you defined in Task 2.2. Your function needs to work under **different shapes** of augmented matrix $[A|b]$. 

The *solve_nonhomogeneous* function should be according to following specifications:
* Take as input the augmented matrix $[A|b]$. 
* Return:
    - None if it has no solution at all. Type: None.
    - the single solution if it only has one solution. Type: np.ndarray.
    - otherwise, return any two different solutions if it has more than one solutions. Type: tuple((np.ndarray, Type: np.ndarray)).
*  Note that the dimensions of the np.ndarray should be 1, especially, one pair of square brackets. See demo outputs below.    

In [19]:
def solve_nonhomogeneous(A_aug):
    # YOUR CODE HERE
    rref = gaussian_elim(A_aug)
    rank_A, rank_aug = 0, 0
    for i in range(A_aug.shape[0]):
        if np.any(rref[i]):
            rank_aug += 1
        if np.any(rref[i][:-1]):
            rank_A += 1
    if rank_A != rank_aug:
        return None
    else:
        res = solve(rref)
        if res.shape[1] == 1:
            return np.squeeze(res)
        else:
            return res[:, 0] + np.sum(res[:, 1:],axis=1), res[:, 0] + 2 * np.sum(res[:, 1:],axis=1)

In [20]:
A = np.array([
    [1, 2, 3, 1],
    [2, 4, 6, 3],
    [7, 8, 9, 4]
])
print(solve_nonhomogeneous(A))
#The result should look like
# None

None


In [21]:
B = np.array([
    [1, 0, 1, 6],
    [0, -3, 1, 7],
    [2, 1, 3, 15]
])
print(solve_nonhomogeneous(B))
#The result should look like
# [ 2. -1.  4.]

[ 2. -1.  4.]


In [22]:
C = np.array([
    [1, 2, 3, 1],
    [2, 4, 6, 2],
    [7, 8, 9, 4]
])
print(solve_nonhomogeneous(C))
#The result should look like
# (array([ 1. , -1.5,  1. ]), array([ 2. , -3.5,  2. ]))

(array([ 1. , -1.5,  1. ]), array([ 2. , -3.5,  2. ]))


We will evaluate your code with multiple different matrices.

In [23]:
def test_nonhomogeneous_no_solution():
    import random
    for i in range(1000):
        m = np.random.randint(low=3, high=6)
        n = np.random.randint(low=3, high=6)
        a = np.random.randn(m, n)
        a_ = a.copy()
        # create matrices whose rows conflict
        cflt = random.sample(range(0, m), np.random.randint(low=2, high=m + 1))
        duplicate = a[cflt[0]]
        for row in cflt:
            a[row] = duplicate
            a[row][-1] = np.random.normal(loc=a[row][-1])
        if solve_nonhomogeneous(a):
            print(a_, '\n')
            print(f'the solution should be None, but got {solve_nonhomogeneous(a)}')
            return False
    return True

def test_nonhomogeneous_single_solution():
    # test square A
    for i in range(1000):
        m = np.random.randint(low=3, high=6)
        n = m + 1
        a = np.random.randn(m, n)
        x = np.expand_dims(solve_nonhomogeneous(a), axis=1)
        if abs(np.sum(a[:, :-1] @ x) - np.sum(a[:, -1])) > 1e-6:
            print(a, '\n')
            print('the solution is not correct')
            return False
    test_list = [
        np.array([[1, 1, 1], [1, 3, 3], [2, 2, 2]]),
        np.array([[1, 2, 3, 2], [2, 4, 6, 4], [3, 6, 9, 6], [4, 7, 9, 10], [1, 2, 4, 7]]),
    ]
    # test A with m>n
    for case in test_list:
        x = np.expand_dims(solve_nonhomogeneous(case), axis=1)
        if abs(np.sum(case[:, :-1] @ x) - np.sum(case[:, -1])) > 1e-6:
            print(a, '\n')
            print('the solution is not correct')
            return False
    return True

def test_nonhomogeneous_infinite_solution():
    import random
    for i in range(1000):
        # test A with m=n and m<n whose rows are dependent
        m = np.random.randint(low=2, high=5)
        n = m + np.random.randint(low=1, high=4)
        a = np.random.randn(m, n)
        a_ = a.copy()
        # create matrices whose rows or columns are dependent
        dpdt = random.sample(range(0, m), np.random.randint(low=2, high=m + 1))
        duplicate = a[dpdt[0]]
        for row in dpdt:
            a[row] = duplicate
        x1 = np.expand_dims(solve_nonhomogeneous(a)[0], axis=1)
        x2 = np.expand_dims(solve_nonhomogeneous(a)[1], axis=1)
        if abs(np.sum(a[:, :-1] @ x1) - np.sum(a[:, -1])) > 1e-6 or abs(
                np.sum(a[:, :-1] @ x2) - np.sum(a[:, -1])) > 1e-6 or (x1==x2).all():
            print(a_, '\n')
            print('the solutions are not correct')
            return False
        # test A with m<n whose rows are not dependent
        if n > m + 1:
            x1 = np.expand_dims(solve_nonhomogeneous(a_)[0], axis=1)
            x2 = np.expand_dims(solve_nonhomogeneous(a_)[1], axis=1)
            if abs(np.sum(a[:, :-1] @ x1) - np.sum(a[:, -1])) > 1e-6 or abs(
                    np.sum(a[:, :-1] @ x2) - np.sum(a[:, -1])) > 1e-6 or (x1==x2).all():
                print(a_, '\n')
                print('the solutions are not correct')
                return False
    # test A with m>n whose rows are dependent
    test_list = [
        np.array([[1, 2, 3], [2, 4, 6], [3, 6, 9]]),
        np.array([[1, 2, 3, 4], [2, 4, 6, 8], [1, 4, 7, 9], [1, 2, 3, 4], [2, 4, 6, 8]]),
    ]
    for case in test_list:
        x1 = np.expand_dims(solve_nonhomogeneous(case)[0], axis=1)
        x2 = np.expand_dims(solve_nonhomogeneous(case)[1], axis=1)
        if abs(np.sum(case[:, :-1] @ x1) - np.sum(case[:, -1])) > 1e-6 or abs(
                np.sum(case[:, :-1] @ x2) - np.sum(case[:, -1])) > 1e-6 or (x1==x2).all():
            print(case, '\n')
            print('the solutions are not correct')
            return False
    return True

print(test_nonhomogeneous_no_solution())
print(test_nonhomogeneous_single_solution())
print(test_nonhomogeneous_infinite_solution())

True
True
True


## Task 3: Gram-Schmidt orthogonalization

The Gram-Schmidt algorithm is used for finding an orthonormal basis for the subspace spanned by a set of vectors.

Given a linearly independent set of vectors $S = \lbrace \mathbf{v_1}, \mathbf{v_2}, ..., \mathbf{v_n} \rbrace$, an orthogonal set $S' = \lbrace \mathbf{u_1}, \mathbf{u_2}, ..., \mathbf{u_n} \rbrace $ can be generated under this procedure:


$\mathbf{u_1} = \mathbf{v_1}$\
$\mathbf{u_2} = \mathbf{v_2} - \textrm{proj}_{\mathbf{u_1}}(\mathbf{v_2})$\
$\mathbf{u_3} = \mathbf{v_3} - \textrm{proj}_{\mathbf{u_1}}(\mathbf{v_3}) - \textrm{proj}_{\mathbf{u_2}}(\mathbf{v_3})$\
...\
$\mathbf{u_n} = \mathbf{v_n} - \sum_{i=1}^{n-1}\textrm{proj}_{\mathbf{u_i}}(\mathbf{v_n})$,

where $\textrm{proj}_{\mathbf{u}}(\mathbf{v}) = \dfrac{\langle \mathbf{u}, \mathbf{v} \rangle}{\langle \mathbf{u}, \mathbf{u} \rangle}\mathbf{u}$

The orthogonal set is not normalized, you can normalize it by $\mathbf{e_i} = \dfrac{\mathbf{u_i}}{||\mathbf{u_i}||}$

---
**Read more:** https://en.wikipedia.org/wiki/Gram–Schmidt_process

---
**Task 3.1**: Implement a function that finds an orthonormal basis of row vectors for matrix $A$. The *gram_schmidt* function should be according to following specifications: 
* Take as input any matrix $A$.
* Return a matrix with the orthonormal basis vectors as the rows.

---
**NOTE**: The resulting basis should be orthonormal, so each basis vector should be of norm 1.

In [24]:
# Find orthonormal basis using gram-schmidt 
def gram_schmidt(A):
    A = A.T
    res = np.copy(A[:,0:0])
    for i in range(0, A.shape[1]):
        v = np.copy(A[:,i]).astype(np.float64)
        for j in range(0, res.shape[1]):
            u = res[:,j]
            diff_rate = (v@u)/(u@u)
            v -= diff_rate * u
        if (abs(sum(v * v)) > 1e-6):
            res = np.c_[res, v]
    res = res / np.sqrt(np.sum(res * res, axis = 0))
    return res.T

In [25]:
A = np.array([[0, -1, 2, 0, 2],
              [1, -3, 1, -1, 2],
              [-3, 4, 1, 2, 1],
              [-1, -3, 5, 0, 7]])

print(gram_schmidt(A))

#The result should look like
# [[ 0.         -0.33333333  0.66666667  0.          0.66666667]
#  [ 0.37796447 -0.75592895 -0.37796447 -0.37796447  0.        ]
#  [-0.57735027  0.         -0.57735027  0.          0.57735027]]

[[ 0.         -0.33333333  0.66666667  0.          0.66666667]
 [ 0.37796447 -0.75592895 -0.37796447 -0.37796447  0.        ]
 [-0.57735027  0.         -0.57735027  0.          0.57735027]]


We will evaluate your code with multiple different matrices.

---
**TASK 3.2:** Implement a function that accepts a matrix and returns TRUE if all the rows of that matrix are orthogonal to one another, and each one of them is of length 1. Use this function to verify the output of your *gram_schmidt* function is actually correct. Again, you must program this function yourself, rather than relying on a library function.

You can check whether your algorithms work using the last 6 lines in the code given below.

In [26]:
def orthogonality_checker(A):
    # YOUR CODE HERE
    A = A.T
    is_orthogonal = True
    for i in range(0, A.shape[1]):
        v = A[:,i]
        if (abs((v@v) - 1.0) > 1e-6):
            return False
        for j in range(0, i):
            u = A[:,j]
            if (abs(v@u) >1e-6):
                return False
    return True

true_test = np.eye(3,3)
false_test = np.ones((3,3))
print('\nCHECKING TRUE TEST (SHOULD RETURN TRUE):')
print(orthogonality_checker(true_test))
print('\nCHECKING FALSE TEST (SHOULD RETURN FALSE):')
print(orthogonality_checker(false_test))


CHECKING TRUE TEST (SHOULD RETURN TRUE):
True

CHECKING FALSE TEST (SHOULD RETURN FALSE):
False


We will evaluate your code with multiple different matrices.

In [27]:
def gram_schmidt_alt(A):
    A = A.T
    res = np.copy(A[:,0:0])
    for i in range(0, A.shape[1]):
        v = np.copy(A[:,i]).astype(np.float64)
        for j in range(0, res.shape[1]):
            u = res[:,j]
            diff_rate = (v@u)/(u@u)
            v -= diff_rate * u
        if (abs(sum(v * v)) > 1e-6):
            res = np.c_[res, v]
    res = res / np.sqrt(np.sum(res * res, axis = 0))
    return res.T

def orthogonality_checker_alt(A):
    # check orthonormality: for an orthonormal matrix A@A.T = I
    is_orthogonal = (np.sum(np.abs((A.T @ A - np.eye(A.shape[1])) ** 2)) < 1e-6)
    return is_orthogonal

def test_gram_schmidt_b():
    for i in range(100):
        m, n = np.random.randint(low=2, high=8, size=2)
        m, n = min(m, n), max(m, n)
        a = np.random.rand(m, n)
        orthonormal_basis = gram_schmidt(a)
        if not orthogonality_checker_alt(orthonormal_basis.T):
            return False, a
    return True, 0

def test_gram_schmidt_c():
    for i in range(100):
        m, n = np.random.randint(low=2, high=8, size=2)
        a = np.random.randint(low=0, high=3, size=(m, n))
        orthonormal_basis = gram_schmidt(a)
        if not orthogonality_checker_alt(orthonormal_basis.T):
            return False, a
    return True, 0

def test_gram_schmidt():
    try:
        A0 = np.array([[1, 2], [2, 3], [3, 4]]).T
        basis_A0 = gram_schmidt(A0)
        a0_test = orthogonality_checker_alt(basis_A0.T)
    except:
        a0_test = False
    try:
        A1 = np.array([[0, 1, -3, -1],
                       [-1, -3, 4, -3],
                       [2, 1, 1, 5],
                       [0, -1, 2, 0],
                       [2, 2, 1, 7]]).T
        basis_A1 = gram_schmidt(A1)
        a1_test = orthogonality_checker_alt(basis_A1.T)
    except:
        a1_test = False
    try:
        b_test, _ = test_gram_schmidt_b()
    except:
        b_test = False
    try:
        c_test, _ = test_gram_schmidt_c()
    except:
        c_test = False
    print("Test A0", "Pass" if a0_test else "Fail")
    print("Test A1", "Pass" if a1_test else "Fail")
    print("Test B", "Pass" if b_test else "Fail")
    print("Test C", "Pass" if c_test else "Fail")

def test_orthogonality_checker():
    for i in range(100):
        m, n = np.random.randint(low=2, high=8, size=2)
        m, n = min(m, n), max(m, n)
        a = np.random.rand(m, n)
        orthonormal_basis = gram_schmidt_alt(a)
        if not orthogonality_checker(orthonormal_basis):
            print("Test Checker Fail")
    print("Test Checker Pass")

test_gram_schmidt()
test_orthogonality_checker()

Test A0 Pass
Test A1 Pass
Test B Pass
Test C Pass
Test Checker Pass
